Unit Testing Frameworks task is completed
NadzeyaKiz/test_automation_csharp pull request #13
Opened 2023-07-31 20:01 UTC by NadzeyaKiz

Task is done

2023-08-04 15:25 UTC, MariaEroshevich requested changes

2023-08-04 15:25 UTC, MariaEroshevich commented on Code/TestProject1/CalcNUnitTests.cs
> +        public void AddReturnsCorrectSumTest(double a, double b, double expectedSum, string testcaseDescription)
No need to make the description as test parameter.

2023-08-04 15:25 UTC, MariaEroshevich commented on Code/TestProject2/CalcXUnitTests.cs
> +        public void isPositiveReturnsCorrectValueTest(double number, bool expectedValue)
it is better to split negative and positive verifications to different test methods.

2023-08-04 15:25 UTC, MariaEroshevich commented on Code/TestProject2/CalcXUnitTests.cs
> +        [InlineData(5, false)]
it is better to split negative and positive verifications to different test methods.

2023-08-04 15:25 UTC, MariaEroshevich requested changes

2023-08-04 15:25 UTC, MariaEroshevich commented on Code/TestProject1/CalcNUnitTests.cs
> +using CSharpCalculator;
duplicate

2023-08-07 20:16 UTC, NadzeyaKiz commented on Code/TestProject1/CalcNUnitTests.cs
> +using CSharpCalculator;
deleted

2023-08-07 20:16 UTC, NadzeyaKiz commented on Code/TestProject2/CalcXUnitTests.cs
> +        public void isPositiveReturnsCorrectValueTest(double number, bool expectedValue)
done

2023-08-07 20:34 UTC, NadzeyaKiz commented on Code/TestProject1/CalcNUnitTests.cs
> +        public void AddReturnsCorrectSumTest(double a, double b, double expectedSum, string testcaseDescription)
comment applied

2023-08-11 20:52 UTC, MariaEroshevich approved these changes

2023-08-30 16:52 UTC, merged