CSharp_oop_1 Homework_1 completed
NadzeyaKiz/test_automation_csharp pull request #4
Opened 2023-06-15 13:13 UTC by NadzeyaKiz

Homework_1 is done. I made an extended version of Task 2 and only then read Task 3 conditions. So I decided to combine them into one task (all necessary checks and requirements are implemented).

2023-06-16 11:32 UTC, dnnyhlwdplc approved these changes

2023-06-16 11:37 UTC, dnnyhlwdplc requested changes

2023-06-16 11:37 UTC, dnnyhlwdplc commented on Code/CSharp_oop_1/Homework_1.cs
> +        public void PrintReceipt(string[] itemNames, double[] itemPricies, double[] itemQuantities, double[] toPayForItems)
I suppose you forgot about task 3

2023-06-16 14:17 UTC, NadzeyaKiz commented on Code/CSharp_oop_1/Homework_1.cs
> +        public void PrintReceipt(string[] itemNames, double[] itemPricies, double[] itemQuantities, double[] toPayForItems)
All done

2023-06-20 02:23 UTC, dnnyhlwdplc approved these changes

2023-06-21 14:17 UTC, merged